[package]
name = "pastel"
description = "Simple bitmap editor for Redox OS"
repository = "https://github.com/pastel.git"
version = "0.0.14"
keywords = ["orbital", "redox", "editor", "graphics"]
authors = ["Robby <robbycerantola@gmail.com>"]


[dependencies]
orbclient = "0.3.9"
orbtk = { git = "https://github.com/robbycerantola/orbtk.git" }
#orbtk = { path = "/home/robby/orbtk"}
orbimage = "0.1.15"
image = "0.12.4"


[features]
debug = []


