[package]
name = "pastel"
description = "Simple paint canvas"
repository = "https://github.com/pastel.git"
version = "0.0.3"
keywords = ["orbital", "redox", "ui", "graphics"]
authors = ["Robby <robbycerantola@gmail.com>"]


[dependencies]
orbclient = "0.3.8"
orbtk = { git = "https://github.com/robbycerantola/orbtk.git"}
#orbtk = { path = "/home/robby/orbtk"}
orbimage = "0.1.15"
image = "0.12.4"
#num-rational = "0.1.36"

[features]
colored = []
