[package]
name = "pastel"
description = "Simple paint canvas"
repository = "https://github.com/pastel.git"
version = "0.0.2"
keywords = ["orbital", "redox", "ui", "graphics"]
authors = ["Robby <robby@gmail.com>"]


[dependencies]
orbclient = "0.3.4"
orbtk = { git = "https://github.com/robbycerantola/orbtk.git"}
orbimage = "0.1.15"
image = "0.12.4"

[features]
colored = []
